---
abstract: unknown
author:
  - 'Emmanuel Rodriguez <potyl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-SendGrid-SmtpApiHeader
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 0
version: 0.01
x_bugtracker: https://github.com/potyl/perl-Mail-SendGrid-SmtpApiHeader/issues
x_homepage: https://github.com/potyl/perl-Mail-SendGrid-SmtpApiHeader
x_repository: https://github.com/potyl/perl-Mail-SendGrid-SmtpApiHeader
