--- #YAML:1.0
name:               Mail-SendGrid-SmtpApiHeader
version:            0.02
abstract:           ~
author:
    - Emmanuel Rodriguez <potyl@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:  0
resources:
    bugtracker:  https://github.com/potyl/perl-Mail-SendGrid-SmtpApiHeader/issues
    homepage:    https://github.com/potyl/perl-Mail-SendGrid-SmtpApiHeader
    repository:  https://github.com/potyl/perl-Mail-SendGrid-SmtpApiHeader
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
